[pytest]
# path to tests folder
testpaths = tests

# test name conventions
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

# ignore folders
norecursedirs =
    .git
    .tox
    venv
    dist
    build
