name: Publish conda package to Anaconda Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Prepare build environment
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git git-lfs

      - name: Install conda
        run: |
          curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda
          ~/miniconda/bin/conda update -n base -c defaults conda

      - name: Build conda environment
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda config --prepend channels conda-forge
          conda config --prepend channels bioconda
          conda config --show channels
          conda env create -f environment-dev.yml
          conda activate package_name
          conda install -c conda-forge conda-build anaconda-client

      - name: Build package
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate package_name
          conda build --croot ../conda-bld .

      - name: Upload package to Anaconda Cloud
        env:
          ANACONDA_USER: ${{ vars.ANACONDA_USER }}
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate package_name
          anaconda --token da-bd98c6a1-1fff-43d6-a442-b2543b4428df \
            upload --user davidrich27 \
            ../conda-bld/noarch/*.conda \
            --force
